spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring_Data_Jpa?createDatabaseIfNotExist=true
    username: root
    password: ayush@123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

